apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - carts/app.yaml
  - catalog/app.yaml
  - orders/app.yaml
  - payment/app.yaml
  - shipping/app.yaml
  - users/app.yaml
  - front-end/app.yaml
