apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-sockshop
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: carts
  endpoints:
  - port: http
    interval: 30s
