apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../core

resources:
  - carts/db.yaml
  - catalog/db.yaml
  - orders/db.yaml
  - payment/db.yaml
  - shipping/db.yaml
  - users/db.yaml

patchesStrategicMerge:
  - carts/app.yaml
  - catalog/app.yaml
  - orders/app.yaml
  - payment/app.yaml
  - shipping/app.yaml
  - users/app.yaml
